import { renderOperations } from "./scripts/operations.ts";

import type { Config } from "automd";

export default {
  generators: {
    // Renders the modifiers table from `scripts/operations.ts`. The samples it
    // links to are generated by `pnpm gen:operations`, which runs automd too.
    "ipx-operations": {
      name: "ipx-operations",
      generate: () => ({ contents: renderOperations() }),
    },
  },
} satisfies Config;
