name: autofix.ci
on: { push: {}, pull_request: {} }
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm build --stub
      - run: pnpm lint:fix
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with: { commit-message: "chore: apply automated updates" }
